name: geo_utils
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  dart_geohash: ^2.0.2
  flutter:
    sdk: flutter

  google_maps_flutter_platform_interface: ^2.4.0

  latlong2: ^0.9.0


  static_analyze_av: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  latlong2: ^0.9.0

flutter:
  uses-material-design: true

